### ISSUE TITLE
tomcat proxycas - remove 8443 SSL port

### ISSUE THREAD

**Issue by pmauduit** [georchestra/ansible#115]
It is not in use anymore, and it makes the serverspec testsuite fail:

```
  1) Port "8443" is expected to be listening
     On host `georchestra'
     Failure/Error: it { should be_listening }
       expected Port "8443" to be listening
       /bin/sh -c ss\ -tunl\ \|\ grep\ -E\ --\ :8443\\\ 
       
     # ./spec/georchestra/georchestra_spec.rb:52:in `block (2 levels) in <top (required)>'

```

**Comment by landryb** [comment]
ok to remove, but why is the testsuite failing ? 4f91386f6e23726dc8b0c3e43cf7707f0a3f313b still leaves it listening afaict...

**Comment by pmauduit** [comment]
because there is an issue with the certificates / private key pair, and tomcat is unable to configure the connector correctly:

```
<2>Failed to initialize component [Connector[HTTP/1.1-8443]]
<2>org.apache.catalina.LifecycleException: Protocol handler initialization failed
<2>    at org.apache.catalina.connector.Connector.initInternal(Connector.java:1049)
<2>    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
<2>    at org.apache.catalina.core.StandardService.initInternal(StandardService.java:558)
<2>    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
<2>    at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:1045)
<2>    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
<2>    at org.apache.catalina.startup.Catalina.load(Catalina.java:724)
<2>    at org.apache.catalina.startup.Catalina.load(Catalina.java:746)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
<2>    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
<2>    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
<2>    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
<2>    at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
<2>    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:472)
<2>Caused by: java.lang.IllegalArgumentException: Alias name [null] does not identify a key entry
<2>    at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99)
<2>    at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
<2>    at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:246)
<2>    at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1193)
<2>    at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1206)
<2>    at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:597)
<2>    at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:80)
<2>    at org.apache.catalina.connector.Connector.initInternal(Connector.java:1046)
<2>    ... 13 more
<2>Caused by: java.io.IOException: Alias name [null] does not identify a key entry
<2>    at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.java:349)
<2>    at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246)
<2>    at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97)
<2>    ... 20 more
<2>
```
