### ISSUE TITLE
Mapstore2 Could not instantiate appender named "fileAppender".

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/ansible#82]
Error get from logs on mapstore2 startup maybe same as https://github.com/georchestra/georchestra/issues/3149

Tested and reproduced with artifact ids : 

georchestra-mapstore-67461592.zip
georchestra-mapstore-54883163.zip

- **tomcat/georchestra/logs/catalina.out**

```
<6>At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
log4j:ERROR Could not instantiate class [org.apache.log4j.rolling.RollingFileAppender].
java.lang.ClassNotFoundException: org.apache.log4j.rolling.RollingFileAppender
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
...
log4j:ERROR Could not instantiate appender named "fileAppender".
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/srv/tomcat/georchestra/webapps/mapstore/WEB-INF/lib/slf4j-log4j12-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/srv/tomcat/georchestra/webapps/mapstore/WEB-INF/lib/slf4j-log4j12-1.5.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
<6>Deployment of web application archive [/srv/tomcat/georchestra/webapps/mapstore.war] has finished in [8,058] ms
<6>Starting ProtocolHandler ["http-nio-8280"]
```
- **tomcat/georchestra/logs/localhost.2021-06-24.log**

> java.io.FileNotFoundException: /srv/tomcat/georchestra/webapps/mapstore/WEB-INF/lib/uom-lib-common-1.0.2.jar

```
24-Jun-2021 17:37:22.767 SEVERE [Catalina-utility-2] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	java.lang.IllegalStateException: java.io.FileNotFoundException: /srv/tomcat/georchestra/webapps/mapstore/WEB-INF/lib/uom-lib-common-1.0.2.jar (No such file or directory)
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:101)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:256)
		at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:282)
...
24-Jun-2021 17:37:22.767 SEVERE [Catalina-utility-2] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	java.lang.IllegalStateException: java.io.FileNotFoundException: /srv/tomcat/georchestra/webapps/mapstore/WEB-INF/lib/uom-lib-common-1.0.2.jar (No such file or directory)
		at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.getArchiveEntry(AbstractSingleArchiveResourceSet.java:101)
		at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:256)
		at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:282)
```

`masptore/` return 404 but seems deploy.

**Comment by Gaetanbrl** [comment]
> masptore/ return 404 but seems deploy.

Missing target-mapping entry for mapstore

```
nano security-proxy/targets-mapping.properties`
mapstore=http://localhost:8280/mapstore/
```

**Comment by pierrejego** [comment]
Corrected with commit [695c77c7475dc18fe9b260a67f084d00107bb1b](https://github.com/georchestra/datadir/commit/5695c77c7475dc18fe9b260a67f084d00107bb1b)

log4j with rolling appender to log4j2
